seq1 = """GGCATAAGCAGAGGATTTTATAACAATGGAAATAAACCCATATCTACTCATGTTAAACAATGATATAACG
TCAATGATATCATTGACATACCCATATACTGGGGCACCTCCTATGTCACATGGAACATCGACCAAATACT
CAATGGAGACTGTGTCAAGAACTTACTCCTACAGTAGAACTAAAAAAGAGGTACCTTCGGGAATATTCCC
AATAGAGAGAAGGAAATTCTGTAACACAATAGAAGACAAAGAAAACCTAGAAAAACCGAATGGAAATGTT
GATATAAATTTCATGTTATCGCTGGCAGAAATGCTGGAAGAAAAGATGGGGAAAGGGTTCTTCAAATTCT
GTGCCAATGAAGCTGAAGCTGAAATTTTGAAGATGCACTTCAGCAAGCTCACTGAAGGAAGGCAAACTTA
TGACTGGACAAGTGAAAGAAATATGCCAGCAGCCACCGCTCTTCAGCTAACAGTAGACGCTATACAAGAA
ACACAGGGAACATTCAAAGGAACTACCATGGTTGAATATTGCAACAAGATATTAGAAATGATGGATTGGC
CGGAAGTGAAATTCAAAAAGGTCAGAATGATTGTTCAGAGGCATTGGGACCCGAAAACCAAAAAAGAAAT
AAAAATGAAGTCTCCAACATTGATGATAACAAAGATTGGAAGAGAAGAATTCATAAAGAGGATATGCACG
ATAAATACCATGGCCAAAGACGGAGAAAGAGGAAAATACAAAAGAAGAGCTATAGCCACCCCCGGGATGG
GAATCAGGCCATTCTCAAAAATTGTGGAAACTTTAGCACAAAAGATTTGTGAGAGACTAGCAGAGAGCGG
TTTGCCTGTTGGGGGAAATGAGAAGAAAGCCAAACTAAAAACTACGGTCTCTTCAACAAACTCAAAACTA
CAAGAAGGGCAGTTCATGGTAAACATAACAGGGGACAACAGCAAGTGGAATGAATGTCAGCAACCAGAAG
CTTATCTTGCAATGTTGGCATACATTACTAAAGACAGCAGCAACTTAATGAAAGATCTCTGCTCAGTAGC
ACCAACATTGTTCTGCAATAAGTACGTAAAAATGGGACAAGGTTTCCGAGCAAAAAACAAAAGAAAAACC
AAAGAAATAGTGATACCCGCAAAAAAGATGAAAGAAAGGAAAGAATTGATGAACGCGGAATGGAGGGACC
TATTTGAAACAATAGAACCTTACATGGATGGAGAGTGCTGCTTCTTGGGGGGAGGAATGCTGATGGGAAT
GTTTAACATGTTGTCAACTGTTTTTGGAGTCATGACATTAAATTACAGGGAGGAAGCATTGGCCAGAAGG
AACTGTTACTGGACTGGGCTACAAAGTTCAGATGATTTTGTGCTCTTTTGCATCTCTAGGACTTGGCCAG
AGATGGAGATGACTATTCTAAAATTCATCGCTGTTTGCAAGTTGATGGGAATAAACATGTCTTTGGAAAA
ATCCTACGGGTGCTTGCCTGAACTTTTTGAGTTCACAAGCATGTTCTTTTCCGGGGATTTTGTCTCAAAC
ATAGCCTTGGAGTTACCTGCTTTCACAACAGCTGGAATGAATGAAGGAACCGACTTCACAGCTGCGATGT
CTGTCATAAGAACAAACATGATTAATAATGGACTTTCTCCTGGGACTGCTTTAATGGCCCTGCGAATTTG
TCTGCAGGAATTTAGAGCAACATACAGAGTACACCCTTATGATTCTGGAGTGAAGAATCATCGAATGAAA
ATCATAAGGAAATTCATTGAAACTATTGAAAACAAAGATGGATTGCTGATATCAGATGGCGGGAAATTAA
TGAACAATATCTCAAGTTTGCACATCCCTGAAGAAATATTGAAAGAGGATTTGATGGATCCCTCCTACAG
GAACAGAGTTTTCAATCCTAGGAACCCCTTTACACAGTTTGAGAAGACAGTTGACATCTTTAAGGCAAGT
GGACCTATAAGGGTAGAGGAGAACGAGGCAGTTGTATCAACGCATTCCTTTAGAACAAGGAGCAATAGGA
CATTGCTAAATACAGACATGAGGGCAATGGCTCTCGAAGAGAAAAGATACCAAGTTGTTTGCAACATGTA
CCGATCGGTCTTCGAAAGTGCAGACGTTAACACCCCAATAGGATCAATGTCGATGGGAGAGGCAATTGAA
GCCAAAATCCTTGACCGGGCCAGAACCCAGTTTGAAAATGGAATCATAGGGGGAGAAGAATATTCTGAAA
TCAAAAGACTAATCGAGGACGCCAAGCGTCAACGACTGTCTGTTTAAGCTTTGCGTTGTTTAATAACAGA
AAAATCCTCTTGCTACTGCT""".replace('\n', '')

seq2 = """GGCATAAGCAGAGGATGTCACTACTATTAACGCTCGCAAAAGAGTATGCAAATCTCACAAAGGATAAGAA
ATCATGCAAATTGCTGTCGCAAGGGACCGTGTCAAGCTACACCACTTTTAAGAAATGGACAACATCGAGA
AAAGAGAAAAACCCATCCCTTCGAATGAGATGGGCAATGGGAAGCAAGTTCCCAATTATGGCAAACAGAG
AAATTTTGGAAGAAGCTGGGATACCAGAACAATGGGAAGGGATAGACCTTTGGTCAAAAAAGGATGATGT
TTCAAAGTTGGGGATGGTGTTAGCGTCTCCAGCAGCCATAACTTACTGGAATTTTTGTGGACCTGGAGTG
GACAATTCTTCTGTAATAAAAGATGTTTATAAAGCAAAATTTATGAAAAAAGAAAGATGGAGAGAGACTC
TATGGGGACCAATGAACTTTGAATTGGTGGGTAAACAAAGAAGAGTGGTTGAAACTCAACCAGTGGAAAT
AAAGCTAAACCAAAAAGAAATAAAAGAACTAACGATGTGGGTTCTTTTTGAAGATGAAGCAAACCTTGCA
AGCAAATTCATACAGGAAAATTTCTCACTTGTCCTGTCATTAAGAGAACTTTACAAGGGAAAGGCAGTAA
ATAAAGATGTTGCAGCTTTCATGATTGCCCACCAATTTTCTCCCGAGAAGAGGTTCTTACCCACTTTTGG
CCCCATTAGACCAGAAAGAATGGAGCTACTCCACTGTTTAGGGGGTGATTTCTGGAAGATAGAGGCAGTA
ACTGCAGGGAGCCTGAACGAAGAACAAAAGAAGAGAGATGTTAGAGCAGTTGCTAGAAAAATTTGCCTTA
GAGCAAGTGTGGACTTATTTACTCCAGCAGAGAAGATAAGGGACTATATAGCAAGTGTGACAATGAGATT
TGGAACAGTAGAAAGAACATTCGAAGACGTAATAAGAAACAGTGATGACATATCTGCGGAAGTAACCTTA
TGCAAGGCGGCACTTGGGTGCGAATTGGGCAAAAGCATGAGCTTTGGGAATCTAAATCTGAGGAAAGTCA
GTGGAGAAGCAGAAACAATGGAAAAAACAGTATATTGGGGATTAAAGCCCATAAAATATAAATGCTGGAG
AGGAGAGGAAACATTTTATTGTGAACTGAGGAAGGTAACTTGTATGTTTAGAAGGTCTGAAGGCCTAGAT
TGGGCTAACATTGGACCTGGTTCACCTGAAGAAAGAAGAGAGCTTTTGGCAATGGTGATGATATTCTGCA
GAGATGGGAGATTCTTTGAATCTGCACCAGTTAATATTGATGAATCATTCTTTAGGACAAGACTGAATAA
AGAAATACCTTATCAATATGTGCTGCTAAAATGGGTAAGGCAATCGAGAGACAACTTGGATGCCTTGTTG
AGTACAAGAGGACTAATACCTGCTCATATTGGACAATTCGGAAAAGGAATGGGAATAGATGGAAGTAGCT
CATCTTCTATGGTTTACAAGGGAGTCATGTTGTCGAAGACACCGATAGACATAGTGGAGAGCAAAGAGAA
GCACAGACTGTTTTTAAATGACAATATAGAAGCAGTGACAGAGAGAGGAGCAATGGTTGCATCCATAATG
GACCTATCAGAGGATAATAGAGAAACATTTAACGATGTGACTTTTAACCATGTCGACTTAGCTGTTCTCA
AAGATGAAAAGACTGCAATAATAAAGATATATCGATCACTAGTGGAAAGAATAAACACTGATGATGATGG
CCTACCTGCTTTGATAATGGGTAAAAGATATTTAGAGTTGTATCAATTAGATGAAGTAAAAGACGCGGTC
GGGCTAATACCAAAAAGGATGCTGGGGGCGTATTCCTACCAAGCAAGACAGCTCATACAGTCACAGATCA
AAAATGACAGTTATAGCCTTCCTGAAATAATAAAGTTACTGCCCTTCTGTTACAGCCCTCCAAAGAAAAT
GTTATTTGATGGGACTTTCCATTTCAAAAATCAAATGTATGTTAGGCCTGGAATAAACACAAACCTTTTC
AGTTTTAGTAAGACCGACAAAAGCAAGATATATGTGAACGGAAGCGCAGTAAAAATAAAGCTTGTGCTCG
GAGACGATGAAATGGACACCAGTCTTGCCTTTGTTGAAGGATTTCAAGTTTGTGAATATGATCCAAGAGC
ACCTTTGATACCAAGAAGAGATTTGAGACTGATTGGGTTCGGAAAGAAAGTTAGAGTTTTTGTTGGTCAG
GGACAGGAGAAAACCCTGGTGAGGACGAGCTCCAAAAGAGCCGCCTCCCATGATGTAAGCAAAAACATTC
GTAGAATGCGTCTGGAAGTTTGAAGCACATTGAAAAAATCCTCTTGCTACTGCT""".replace('\n', '')

seq3 = """GGCATAAGCAGGAGATTATTAAGCAATATGGACTCAACAAAAGCCCAAACGCCTGAAGAGCAGAGAGCAA
AGAATGCCAAAACCATCCTTGAGAACATACAGATATATGAAAGGATGTGTGATCTCTTTGGGGTGTCAGA
AGATGACAAACTGATAATTGAGAACAGTATTTCAATTGAGAGGATGATAAGAGTTGTAACAGATAAGAAA
TACCAAGACAAAAAACTAAAGAATGCTGGAAGTGATCCTGAAAAGATTGCAAATGCAGGGAAAGTTTTCT
GTCGATTGGTGGAGTCAACAGCTGGGAAATGTAGTGCAAGATTGGGAATGGCACTGAAACCCAACGTTGA
GGCAGTCCTGACCGATGTACTCGGGAATGAACTGGATAGGGCTGCTGTGCTTGGGAAAAGAATGGGGTTT
TCAGCAATGTTCAAATCAAACCTGGAAGAGGTTTTGTACCAAAGAGGAAAGAATCAGCTTAAAAAGAGGA
ATGCTGCAGAAACTTTCACTCTTTCACAAGGTGCTTCGCTAGAGGCAAGATTTAGGCCCATAATGGAAAA
ACACCTAGGTGTTGGGACTGTTGTGGCGTCAATAAAGAATATCCTGGCAAGCAAAAAGAACGGGAACTAC
AGGAACAAGATGGTGAGGAAACCTGGAGGAAACAGAGAGAGCTGGTCACCATTGGAGAGAGAGATATCCT
TTCTGAACAAGAAGTTGTTTCCTGGACCAATGAGGCAGCTCTGCAAGAAATTCGAATACTTGAACGAGCA
AGAGAAGCAACTGGCCTTAAACCTTATGCTGGATGCAAGTCTCATCCTAAAACCGCAAGTGACTCACAAA
ATGATAATGCCTTGGTCAATGTGGCTGGCTGTGAAGAAGTATGCAGAAATGAACAAGGGATCACCCAGTC
TTGAAGACCTCGCAGCCTATTCTGGAGTAAGAGCCTTTATGGCCTTCAATACAGCTTGCTACATGAGTAA
ATTCACCATTGGGAAGGGAATTGTGGGAGATGCAGAGATCATGGAAAATGGAAACGACAAGATGCAAACT
CTTGCAATGGCTTGTTTTGGACTGGCGTATGAAGACACCGGGATTGTTGCTGCAATGATCTCCCAACCCA
TGAAGAAAAGATATCAGTTGAGAGTGGGGAACTTCAATCCTCCAGAAAAAGGAACAATAAAAGGAACAAG
CGCCGGCTATTTCCACAAGTGGGCTGAATTTGGAAATAGGCTGCCTTTCAACAGTTTTGGAACTGGTGAA
TCCAAACAGATAAGCAACTCAGGAGTGTTTGCAGTGCAGAGGCCCAGCACTACTAACATTCAAAGACTGG
CAGAGCTAATGGCTAGGAATACCGGAGAAACCAGCGACAACTTTACTCAGTTGGTTCAGAAAATAAGAGA
ACAAGTGGGGGCCTTTGCTGATCAAAAAGCAAATCTTCGAGAGTTCACCGGAGGATATATTTATGACATT
ACTGACGTAACGAAGAGCAACCCCAAGATACCTCAGTTGGGTGGGGACTCTTTCTTCTTTGAGTTCACCG
GAAGCGACGTTCCAAGAACTGGAGCCAAAAGAAGAGTGGGAGGAGCTGATGATGTGACCCCTGGAACTTC
CCAGCCCAAGAAAAGAGGAAGGCAAGGTGCCGGAGCAGAATCAAGTATGGACATTGAAACAGTTGGTGAA
GATTAACTCATCTTTGGATGGTTCTGTTGCAGTCCCCAGTGGGTGTTAAAGATGTTGGTTTGTCTTATTT
AACAAAAAATCTCCTTGCTACTGCT""".replace('\n', '')

seq4 = """GGCATAAGCAGGAGATTTAGAAATGTCTAGTGTAATCAGAGAAATCGCAAAGCGATTCTTGGAACAAGCA
ACGATAAACATCGCTGAAGAAGTGGTCAGAGAATATGGAGACCATGAAAGAACAATGATATCTGTTGGAG
TTCATTTCCAAGCTTGCTGCCTTATAAGTGATGAATATACCCTTGAGGATGAGACAACCCCAAGATACGT
TCTTTTGGAGGGATTGAAAAGACAAGAGGCTATAAGCAAGCAGAATAACATTTGCTCCACTTTGGGATTG
GAGCCCTTGAGAAATCTAGCAGATATTTTTGATCGAAAAACAAGAAGATTCCTTGAGGTAGGAATTACAA
AGAGAGAATCCGATGAGTATTACCAGGAAAAGTTCAACAAAATAGGAAATGACATGGACATACATGTTTT
CACATATGAAGGCAAATATTTCAGCAACAATCCCAATGGGTTGGAAGACATCCAAAAGACAAGAATTTTT
ACATTCCTATCTTTTGTGTCAGACGAATTGAGAAAAGAGAACATGTTCACAGAAATGTATGTTACAGAAG
AAGGGGCACCTGAACTTGAAATGTACAAGTCAAAGCTTTTCATTGCGATGAGAGACGAGAGCGTGCCTTT
GCCTTACATAAACTATGAGCACCTTAGGACAAGATGTGAAACATTCAAAAGAAATCAGGCTGAATGCGAA
GCAAAGGTAGCGGATGTGGCTTCACGGCTAAAAATCAAACTGGAACATCTAGAAGAAAATAAACTGCGGC
CGCTAGAGATACCGAAGGAGAAAGAGGCTCCCTATACACACAAATTTTTGATGAAAGATGCTTGGTTCTT
TGCAAAACCTCATGATTCGGAGAGAGCACAACCGCAACAGATATTGTATGATTTCTTTGAAGCAGCAAAC
ATGGGGTTCATGACGACATCCCCAAAACCGATATTCGGAAAGCAAGGACTGATGTATCACTCCCTCTGGG
GGCAGACAAAAAGAGCAATAAAGGACAAGAGAAATGAGTTGGAGCCTTCAGAACAGAGAGACTTCCTTTG
TGGAATTGGAAGAGCCTCCAAGAAAATACAGGAGGACAAATGGCAAGAATCCAGAGAGGAAGAGTTTAAA
CAAGAAGAGACTAAAGGGGCAGCTAAGAGGGGGTTCCCAACATGGTTTAATGAAGAATGGCTTTGGGCAA
TGAGGGACTCAGGGGATGGGGACAATAAAATAGGGGATTGGATACCCATGGCAGAAATGCCTCCCTGCAA
GAATGAGATGGAAGATTATGCAAAAAAGATGTGTGAAGAATTAGAATCCAAAATACAGGGAACAAATTGT
GCTAGGGAAATGTCCAAGTTGATACATACAATTGGGAGCTTACATACAGAATGTAGGAACTTTCCCGGAA
AGGTCAAGATAGTGCCTATATACTGCAGAGGGACACTGAGAGGGGAATCAACTGACTGTTTGTTTGGAAT
AGCAATAAAAGGGAAATCCCATTTAAACAAAGATGATGGAATGTATACTGTTGTAACTTTTGAGTTTTCC
ACTGAAGAACCAAATCCAAGCAAACATGAAAAATATACGGTCTTCGAAGCTGGAACAGTGCCTGTGGAAG
CCGTGGTGTTAACTCCCAAAAGGGAAAGAGTTCTCAAAGAGAAGAAATTGTTCCTTTATTGCAGAACTAC
TGGAATGAGCAAGTTAAAGAACGATTGGTTTTCTAAATGCAGGAGATGTCTTATACCAACAATGGAGACT
GTAGAGCAGATAGTGCTGAAAGAATGCGCTCTGAAAGAAGAAAACAGAGTTTCAGAGATGTTGGAGAATA
AGAGAGCTTGGATTGCCCATGAGAACGGAGAGAATCTTACAAGATTGGTATCAACAAAGCTCAAGGACTT
GTGTAGAATGCTAATTGTGACACAATTTTATTACTGTATATATAACGACAATCAATTGGAAGGATTCTGT
AACGAGCAAAAGAAATTCCTTATGTTTCTTCAAGCAGATAAGGACTCAAAATCTGCATTTACTTTTAATC
AGAAAGGGTTATATGAAAAAATTGAAGAGTGTATTGTCAGCAATCCATTATGTATTTTCCTAGCTGATAG
GCTAAACAAATTATTTCTTGTAGCCAAGTCCAATGGAGCTAAGTACTTTGAATGACCAAAGGCCTTGTAA
TGTTAAAAATCTCCTTGCTACTGCT""".replace('\n', '')

seq5 = """GGCATAAGCAGAGGATATTTTTGACGCAATGGCACAAGAACAACTACTTGCTGAACTTGAGGGATACCTC
AGAGGAGTTAACCCAATGACCAGGCAAACGATTATGAAGTCTGCAAGAGGTGGGATGGATAGTGCTAAGG
AGGCAGCAAAAGCAGCGAAGAAGGGAGAAATGCAACTAACAAGTGGAGAGAGCATAGTGGTGCACATATG
CCTGAGAGCCATGTACCCTGGAATAAAGCCATGGTCAGAAGCCAAAAAAGATCTTGATAAAGCTACAGAA
GGACTGAGTGGAAAAGACTGCAAAAATATAAGAAAAGCTCTGAGGAAGGCAGGAGACCTGACAGGGATAA
AGGAGATGATGATGATGTATGAAATGAGGGAGGACAAAAAAGCAGAAATGGTAGAGCAAATCTACGATGA
CCCAGAGGATTTTACAGAAGATGTAAGGCTTGGGACCGTTGCTGCCTGGCTTCAATGCAAAAACAAAAGG
AGCGAGAAATATCATCACAAGATGTCAATGTCTGGAAGCACTGCACTTGCCTTGGGAGATGCCCAAAAGG
CCGGAATGGCCATAGAAAATATGGCTAGTGTTGTGCCAATGAAAAAAGAGGCCCAGGCACTGCACAAAGA
CGCAGAAGTTTTGATTGAACTGGCAAGAATAGCATATGGGTCAAGAGCAATGGAAGGGCACCTGCAAAAT
GCAATGGACGGAATTGGAAGCAAAGTCAGTGGAATGGCTAATCTTGCCCTAAAAAGGTCAGTTCTTACTT
TGTTAATGTTGGTAATTTGTGGGATCCCCACTTGTGTAAATGCTGAAACTGTGGAAGAATTTTGTAGAAA
GAAACTAAATCAGACGGAAGAAAAGGTTTATGTCCATTGTTTCAATGAGGATGATGGTCGGGCAATGACT
TTAGCTGCTTTGATACTTGGATGCTTTAGTATGCTTTACATTTTAATAAAGGCAATACTGATGCTTTTGT
TGACAATCATAAATGGAAGACCAAATGGAAGTTGGGATGACTTGAAACATGTTGTAAAATGTTTTTCAGA
GACTGGAAGTGAGAACTTCGCCAGGGATATAATGGTCCTGGAATCCAGGCGAGATGGGGAGGAGACAAGC
TCCCCAGAGGAGGGACTAGGCCCTCCATTGAGTGGATTCAATGAAAATGGTGTATTCATGGAAACATTAT
AATCGCGAAAAAATCCTCTTGCTACTGCT""".replace('\n', '')

seq6 = """ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTTTCTATCATCCCGTCAGGCCCCCTCAAAGCCGAGA
TCGCGCAGAGACTGGAAAGTGTCTTTGCAGGAAAGAACACAGATCTTGAGGCTCTCATGGAATGGCTAAA
GACAAGACCAATCTTGTCACCTCTGACTAAGGGAATTTTAGGATTTGTGTTCACGCTCACCGTGCCCAGT
GAGCGAGGACTGCAGCGTAGACGCTTTGTCCAAAATGCCCTAAATGGGAATGGGGACCCGAACAACATGG
ATAGAGCAGTTAAACTATACAAGAAGCTCAAAAGAGAAATAACGTTCCATGGGGCCAAGGAGGTGTCACT
AAGCTATTCAACTGGTGCACTTGCCAGTTGCATGGGCCTCATATACAACAGGATGGGAACAGTGACCACA
GAAGCTGCTTTTGGTCTAGTGTGTGCCACTTGTGAACAGATTGCTGATTCACAGCATCGGTCTCACAGAC
AGATGGCTACTACCACCAATCCACTAATCAGGCATGAAAACAGAATGGTGCTGGCTAGCACTACGGCAAA
GGCTATGGAACAGATGGCTGGATCGAGTGAACAGGCAGCGGAGGCCATGGAGGTTGCTAATCAGACTAGG
CAGATGGTACATGCAATGAGAACTATTGGGACTCATCCTAGCTCCAGTGCTGGTCTGAAAGATGACCTTC
TTGAAAATTTGCAGGCCTACCAGAAGCGAATGGGAGTGCAGATGCAGCGATTCAAGTGATCCTCTCGTCA
TTGCAGCAAATATCATTGGGATCTTGCACCTGATATTGTGGATTACTGATCGTCTTTTTTTCAAATGTAT
TTATCGTCGCTTTAAATACGGTTTGAAAAGAGGGCCTTCTACGGAAGGAGTGCCTGAGTCCATGAGGGAA
GAATATCAACAGGAACAGCAGAGTGCTGTGGATGTTGACGATGGTCATTTTGTCAACATAGAGCTAGAGT
AA""".replace('\n', '')

seq7 = """ATGAAGGCAATACTAGTAGTTCTGCTATATACATTTGCAACCGCAAATGCAGACACATTATGTATAGGTT
ATCATGCGAACAATTCAACAGACACTGTAGACACAGTACTAGAAAAGAATGTAACAGTAACACACTCTGT
TAACCTTCTAGAAGACAAGCATAACGGGAAACTATGCAAACTAAGAGGGGTAGCCCCATTGCATTTGGGT
AAATGTAACATTGCTGGCTGGATCCTGGGAAATCCAGAGTGTGAATCACTCTCCACAGCAAGCTCATGGT
CCTACATTGTGGAAACACCTAGTTCAGACAATGGAACGTGTTACCCAGGAGATTTCATCGATTATGAGGA
GCTAAGAGAGCAATTGAGCTCAGTGTCATCATTTGAAAGGTTTGAGATATTCCCCAAGACAAGTTCATGG
CCCAATCATGACTCGAACAAAGGTGTAACGGCAGCATGTCCTCATGCTGGAGCAAAAAGCTTCTACAAAA
ATTTAATATGGCTAGTTAAAAAAGGAAATTCATACCCAAAGCTCAGCAAATCCTACATTAATGATAAAGG
GAAAGAAGTCCTCGTGCTATGGGGCATTCACCATCCATCTACTAGTGCTGACCAACAAAGTCTCTATCAG
AATGCAGATGCATATGTTTTTGTGGGGTCATCAAGATACAGCAAGAAGTTCAAGCCGGAAATAGCAATAA
GACCCAAAGTGAGGGRTCRAGAAGGGAGAATGAACTATTACTGGACACTAGTAGAGCCGGGAGACAAAAT
AACATTCGAAGCAACTGGAAATCTAGTGGTACCGAGATATGCATTCGCAATGGAAAGAAATGCTGGATCT
GGTATTATCATTTCAGATACACCAGTCCACGATTGCAATACAACTTGTCAAACACCCAAGGGTGCTATAA
ACACCAGCCTCCCATTTCAGAATATACATCCGATCACAATTGGAAAATGTCCAAAATATGTAAAAAGCAC
AAAATTGAGACTGGCCACAGGATTGAGGAATATCCCGTCTATTCAATCTAGAGGCCTATTTGGGGCCATT
GCCGGTTTCATTGAAGGGGGGTGGACAGGGATGGTAGATGGATGGTACGGTTATCACCATCAAAATGAGC
AGGGGTCAGGATATGCAGCCGACCTGAAGAGCACACAGAATGCCATTGACGAGATTACTAACAAAGTAAA
TTCTGTTATTGAAAAGATGAATACACAGTTCACAGCAGTAGGTAAAGAGTTCAACCACCTGGAAAAAAGA
ATAGAGAATTTAAATAAAAAAGTTGATGATGGTTTCCTGGACATTTGGACTTACAATGCCGAACTGTTGG
TTCTATTGGAAAATGAAAGAACTTTGGACTACCACGATTCAAATGTGAAGAACTTATATGAAAAGGTAAG
AAGCCAGCTAAAAAACAATGCCAAGGAAATTGGAAACGGCTGCTTTGAATTTTACCACAAATGCGATAAC
ACGTGCATGGAAAGTGTCAAAAATGGGACTTATGACTACCCAAAATACTCAGAGGAAGCAAAATTAAACA
GAGAAGAAATAGATGGGGTAAAGCTGGAATCAACAAGGATTTACCAGATTTTGGCGATCTATTCAACTGT
CGCCAGTTCATTGGTACTGGTAGTCTCCCTGGGGGCAATCAGTTTCTGGATGTGCTCTAATGGGTCTCTA
CAGTGTAGAATATGTATTTAA""".replace('\n', '')

seq8 = """ATGGATGTCAATCCGACTCTACTTTTCCTAAAAATTCCAGCGCAAAATGCCATAAGCACCACATTCCCTT
ATACTGGAGATCCTCCATACAGCCATGGAACAGGAACAGGATACACCATGGACACAGTAAACAGAACACA
CCAATACTCAGAAAAGGGAAAGTGGACGACAAACACAGAGACTGGTGCACCCCAGCTCAACCCGATTGAT
GGACCACTACCTGAGGATAATGAACCAAGTGGGTATGCACAAACAGACTGTGTTCTAGAGGCTATGGCTT
TCCTTGAAGAATCCCACCCAGGAATATTTGAGAATTCATGCCTTGAAACAATGGAAGTTGTTCAACAAAC
AAGGGTAGATAAACTAACTCAAGGTCGCCAGACTTATGATTGGACATTAAACAGAAATCAACCGGCAGCA
ACTGCATTGGCCAACACCATAGAAGTCTTTAGATCGAATGGCCTAACAGCTAATGAGTCAGGAAGGCTAA
TAGATTTCTTAAAGGATGTAATGGAATCAATGAACAAAGAGGAAATAGAGATAACAACCCACTTTCAAAG
AAAAAGGAGAGTAAGAGACAACATGACCAAGAAGATGGTCACGCAAAGAACAATAGGGAAGAAAAAACAA
AGACTGAATAAGAGAGGCTATCTAATAAGAGCACTGACATTAAATACGATGACCAAAGATGCAGAGAGAG
GCAAGTTAAAAAGAAGGGCTATCGCAACACCTGGGATGCAGATTAGAGGTTTCGTATACTTTGTTGAAAC
TTTAGCTAGGAGCATTTGCGAAAAGCTTGAACAGTCTGGGCTCCCAGTAGGGGGCAATGAAAAGAAGGCC
AAACTGGCAAATGTTGTGAGAAAGATGATGACTAATTCACAAGACACAGAGATTTCTTTCACAATCACTG
GGGACAACACTAAGTGGAATGAAAATCAAAATCCTCGAATGTTCCTGGCGATGATTACATATATCACCAG
AAATCAACCCGAGTGGTTCAGAAACATCCTGAGCATGGCACCCATAATGTTCTCAAACAAAATGGCAAGA
CTAGGGAAAGGGTACATGTTCGAGAGTAAAAGAATGAAGATTCGAACACAAATACCAGCAGAAATGCTAG
CAAGCATTGACCTGAAGTACTTCAATGAATCAACAAAGAAGAAAATTGAGAAAATAAGGCCTCTTCTAAT
AGATGGCACAGCATCACTGAGTCCTGGGATGATGATGGGCATGTTCAACATGCTAAGTACGGTCTTGGGA
GTCTCGATACTGAATCTTGGACAAAAGAAATACACCAAGACAATATACTGGTGGGATGGGCTCCAATCAT
CCGACGATTTTGCTCTCATAGTGAATGCACCAAACCATGAGGGAATACAAGCAGGAGTGGACAGATTCTA
CAGGACCTGCAAGTTAGTGGGAATCAACATGAGCAAAAAGAAGTCCTATATAAATAAGACAGGGACATTT
GAATTCACAAGCTTTTTTTATCGCTATGGATTTGTGGCTAATTTTAGCATGGAGCTACCCAGCTTTGGAG
TGTCTGGAGTAAATGAATCAGCTGACATGAGTATTGGAGTAACAGTGATAAAGAACAACATGATAAACAA
TGACCTTGGACCTGCAACGGCCCAGATGGCTCTTCAATTGTTCATCAAAGACTACAGATACACATATAGG
TGCCATAGGGGAGACACACAAATTCAGACGAGAAGATCATTTGAGTTAAAGAAGCTGTGGGATCAAACCC
AATCAAAGGTAGGGCTATTAGTATCAGATGGAGGACCAAACTTATACAATATACGGAATCTTCACATTCC
TGAAGTCTGCTTAAAATGGGAGCTAATGGATGATGATTATCGGGGAAGACTTTGTAATCCCCTGAATCCC
TTTGTCAGTCATAAAGAGATTGATTCTGTAAACAATGCTGTGGTAATGCCAGCCCATGGTCCAGCCAAAA
GCATGGAATATGATGCCGTTGCAACTACACATTCCTGGATTCCCAAGAGGAATCGTTCTATTCTCAACAC
AAGCCAAAGGGGAATTCTTGAGGATGAACAGATGTACCAGAAGTGCTGCAATCTATTCGAGAAATTTTTC
CCTAGCAGTTCATATAGGAGACCGGTTGGAATTTCTAGCATGGTGGAGGCCATGGTGTCTAGGGCCCGGA
TTGATGCCAGGGTCGACTTCGAGTCTGGACGGATCAAGAAAGAAGAGTTCTCTGAGATCATGAAGATCTG
TTCCACCATTGAAGAACTCAGACGGCAAAAATAA""".replace('\n', '')

seq9 = """ATGGATGTCAATCCGACTTTACTTTTCTTGAAAGTGCCAGTGCAAAATGCTATAAGTACCACTTTCCCTT
ATACTGGAGACCCTCCATACAGCCATGGAACAGGAACAGGATACACCATGGACACAGTCAACAGAACACA
TAAATACTCAGAAAAAGGAAAGTGGACAACGAACACAGAGACTGGAGCACCCCAACTCAATCCAATTGAT
GGACCATTACCTGAGGACAACGAGCCGAGTGGGTATGCACAAACGGATTGTGTATTGGAAGCAATGGCTT
TCCTTGAAGAATCTCACCCAGGGATCTTTGAAAACTCGTGTCTCGAAACGATGGAAATTGTTCAGCAAAC
AAGAGTGGATAAACTGACCCAAGGCCGCCAGACCTATGACTGGACGTTGAATAGAAATCAGCCGGCTGCT
ACCGCATTGGCCAACACTATAGAGGTATTCAGATCGAATGGCCTGACAGCCAATGAATCAGGAAGGTTGA
TCGATTTCCTCAAGGACGTGATGGATTCAATGGATAAGGAAGAAATGGAGATTACAACACATTTCCAGAG
GAAGAGGAGAGTGAGGGACAACATGACCAAGAAAATGGTCACACAGAGAACAATAGGAAAGAAAAAACAA
AGACTGAACAAAAGGAGCTACCTAATAAGAGCACTTACATTGAACACAATGACAAAGGATGCTGAAAGAG
GCAAGCTGAAAAGGAGGGCAATCGCAACACCCGGGATGCAAATCAGAGGATTCGTGTATTTTGTAGAAGC
ACTAGCGAGGAGCATCTGTGAGAAACTTGAGCAATCTGGCCTCCCTGTCGGAGGGAATGAGAAGAAAGCT
AAATTGGCAAATGTTGTGAGGAAGATGATGACTAATTCACAAGATACAGAGCTCTCCTTCACAATTACTG
GGGACAACACCAAATGGAATGAGAATCAAAACCCCCGGATGTTTCTAGCAATGATAACATACATCACAAG
AAACCAGCCAGAATGGTTTAGAAATGTCTTAAGCATTGCTCCTATAATGTTCTCAAACAAGATGGCGAGA
TTAGGAAAAGGGTACATGTTCGAAAGTAAGAGTATGAAGTTACGGACACAAGTACCAGCGGAAATGCTCG
CAAATATTGACCTGAAATACTTCAACAAATCAACAAGAGAGAAAATCGAGAAAATAAGACCTCTACTGAT
AGATGGCACAGCCTCATTGAGTCCTGGAATGATGATGGGCATGTTCAACATGTTGAGTACAGTCTTAGGA
GTTTCAATTCTGAATCTCGGGCAGAAGAAGTACACCAAAACCACATATTGGTGGGACGGACTCCAATCCT
CAGATGACTTCGCCCTCATAGTGAATGCACCGAATCATGAGGGAATACAGGCAGGAGTAGATAGGTTCTA
TAGAACCTGCAAATTAGTTGGGATAAACATGAGCAAGAAGAAATCCTACATAAATCGGACAGGAACATTC
GAATTCACAAGCTTTTTCTACCGCTATGGATTCGTAGCTAACTTCAGTATGGAGTTGCCCAGTTTTGGAG
TGTCCGGGATTAATGAGTCAGCTGACATGAGCGTTGGTGTTACAGTAATAAAGAACAATATGATAAACAA
CGATCTTGGACCAGCAACAGCCCAAATGGCCCTTCAGCTATTTATCAAAGACTACAGATACACATACCGA
TGTCACAGGGGTGATACGCAAATTCAAACGAGGAGAGCATTCGAGCTGAAGAAGCTGTGGGAGCAGACCC
GTTCGAAGGCAGGACTGTTGGTTTCAGATGGAGGGCCAAACCTGTACAATATCCGGAACCTCCACATTCC
AGAGGTCTGCTTGAAATGGGAATTGATGGATGAAGACTACCAAGGCAGGTTGTGTAATCCTATGAACCCG
TTTGTCAGTCATAAGGAAATTGATTCAGTCAACAATGCTGTGGTGATGCCAGCTCATGGCCCAGCCAAAA
GCATGGAGTATGATGCCGTTGCAACCACACATTCATGGATTCCTAAGAGGAATCGCTCCATTCTCAACAC
CAGCCAAAGGGGGATTCTTGAGGACGAACAGATGTACCAGAAGTGCTGCAACCTATTCGAAAAGTTCTTC
CCCAGCAGTTCGTACAGGAGGCCAGTTGGAATTTCCAGCATGGTGGAGGCCATGGTGTCTAGGGCCCGAA
TTGATGCACGAATTGACTTCGAATCTGGAAGGATTAAGAAAGAAGAGTTTGCTGAGATCATGAAGATCTG
TTCCACCATTGAAGAGCTCAGACGGCAAAAATAGTGAATTTAGCTTGTCCTTCATGA""".replace('\n', '')

seq10 = """ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCATTCCATCAGGCCCCCTCAAAGCCGAGA
TCGCACAGAGACTTGAGGATGTTTTTGCAGGGAAGAACGCAGATCTCGAGGCTCTCATGGAGTGGATAAA
GACAAGACCAATCCTGTCACCTCTGACTAAGGGGATTTTAGGGTTTGTGTTCACGCTCACCGTGCCCAGT
GAGCGAGGACTGCAGCGTAGACGGTTTGTCCAAAACGCCCTAAATGGGAATGGAGACCCAAACAACATGG
ACAAGGCGGTTAAATTATACAAGAAACTGAAGAGGGAAATGACATTTCATGGAGCAAAGGAAGTTGCACT
CAGTTACTCAACTGGTGCGCTTGCCAGCTGCATGGGTCTCATATACAACAGAATGGGGACTGTGACCGCA
GAAGGGGCTCTTGGACTAGTATGTGCCACTTGTGAGCAGATTGCTGACGCACAACATCGGTCCCACAGGC
AGATGGCGACTACTACTAACCCACTAATTAGGCATGAGAATAGAATGGTACTAGCCAGCACTACGGCTAA
GGCTATGGAGCAGATGGCTGGATCAAGTGAACAGGCAGCGGAAGCCATGGAAGTTGCAAGTCAGGCTAGG
CAAATGGTGCAGGCTATGAGAACAGTTGGGACTCACCCTAACTCCAGTACAGGTCTAAAAGATGATCTTA
TTGAAAATTTGCAGGCCTACCAGAACCGGATGGGAGTGCAACTGCAGCGGTTCAAGTGAGCCTCTAGTCG
TTGCAGCTAACATTATTGGGATATTGCACTTGATATTGTGGATTCTTGATCGTCTTTTCTTCAAATGCAT
TTATCGTCGTTTTAAATACGGTTTGAAAAGAGGGCCTTCTACGGAAGGAATGCCTGAGTCTATGAGGGAA
GAATATCGGCAGGAACAGCAGAATGCTGTGGATGTTGACGATGGTCATTTTGTCAACATAGAGCTGAAGT
AAAAA""".replace('\n', '')

# Influenza genome sequences (paste your sequences here)
sequences = {
    'seq1': seq1,
    'seq2': seq2,
    'seq3': seq3,
    'seq4': seq4,
    'seq5': seq5,
    'seq6': seq6,
    'seq7': seq7,
    'seq8': seq8,
    'seq9': seq9,
    'seq10': seq10
}

# Restriction enzymes
enzymes = {
    'EcoRI': 'GAATTC',
    'BamHI': 'GGATCC',
    'HindIII': 'AAGCTT',
    'TaqI': 'TCGA',
    'HaeIII': 'GGCC'
}

cleavage_offsets = {
    'EcoRI': 1,
    'BamHI': 1,
    'HindIII': 1,
    'TaqI': 1,
    'HaeIII': 2
}

def find_restriction_sites(sequence, recognition_seq, offset):
    positions = []
    start = 0
    while True:
        pos = sequence.find(recognition_seq, start)
        if pos == -1:
            break
        cleavage_pos = pos + offset
        positions.append(cleavage_pos)
        start = pos + 1
    return positions

def calculate_fragments(sequence_length, cleavage_positions):
    if not cleavage_positions:
        return [sequence_length]
    
    sorted_positions = sorted(cleavage_positions)
    fragments = []
    
    fragments.append(sorted_positions[0])
    
    for i in range(1, len(sorted_positions)):
        fragments.append(sorted_positions[i] - sorted_positions[i-1])
    
    fragments.append(sequence_length - sorted_positions[-1])
    
    return fragments

# Analyze all sequences
all_results = {}

for seq_name, sequence in sequences.items():
    seq_results = {}
    for enzyme_name, recognition_seq in enzymes.items():
        offset = cleavage_offsets[enzyme_name]
        cleavage_positions = find_restriction_sites(sequence, recognition_seq, offset)
        fragments = calculate_fragments(len(sequence), cleavage_positions)
        
        seq_results[enzyme_name] = {
            'positions': cleavage_positions,
            'fragments': sorted(fragments, reverse=True),
            'num_cleavages': len(cleavage_positions)
        }
    
    all_results[seq_name] = seq_results

# 1) Print electrophoresis gel for each genome
print("="*70)
print("TASK A: INDIVIDUAL ELECTROPHORESIS GELS FOR EACH GENOME")
print("="*70)

gel_height = 30
max_length = max(len(seq) for seq in sequences.values())

for seq_name in sequences.keys():
    print(f"\n\n{seq_name.upper()} - Length: {len(sequences[seq_name])} bp")
    print("="*70)
    
    for enzyme_name in enzymes.keys():
        fragments = all_results[seq_name][enzyme_name]['fragments']
        num_cuts = all_results[seq_name][enzyme_name]['num_cleavages']
        
        print(f"\n{enzyme_name}: {num_cuts} cuts, {len(fragments)} fragments")
        print("-" * 50)
        
        for frag_length in fragments:
            migration_distance = int((1 - frag_length / max_length) * gel_height)
            spaces = " " * migration_distance
            band = "█" * 10
            print(f"{spaces}{band}  {frag_length} bp")

# 2) Find common and unique fragments
print("\n\n" + "="*70)
print("TASK B: IDENTIFYING COMMON AND UNIQUE FRAGMENTS")
print("="*70)

# For finding common fragments, we'll use a tolerance approach
# Fragments within ±5 bp are considered "similar"
tolerance = 5

common_fragments = {}
unique_fragments = {}

for enzyme_name in enzymes.keys():
    print(f"\n{enzyme_name}:")
    print("-" * 50)
    
    # Collect all fragments with their sequence names
    all_fragments = []
    for seq_name in sequences.keys():
        fragments = all_results[seq_name][enzyme_name]['fragments']
        for frag in fragments:
            all_fragments.append((seq_name, frag))
    
    # Count occurrences of similar fragment sizes
    fragment_counts = {}
    for seq_name, frag in all_fragments:
        # Check if this fragment is similar to any existing key
        found = False
        for key in fragment_counts.keys():
            if abs(frag - key) <= tolerance:
                fragment_counts[key].append((seq_name, frag))
                found = True
                break
        if not found:
            fragment_counts[frag] = [(seq_name, frag)]
    
    # Identify common fragments (present in all 10 sequences)
    common = []
    for key, occurrences in fragment_counts.items():
        seq_names = set([occ[0] for occ in occurrences])
        if len(seq_names) == len(sequences):  # Present in all sequences
            common.append(key)
    
    common_fragments[enzyme_name] = sorted(common, reverse=True)
    
    # Find unique fragments for each sequence
    unique_fragments[enzyme_name] = {}
    for seq_name in sequences.keys():
        seq_fragments = all_results[seq_name][enzyme_name]['fragments']
        unique = []
        for frag in seq_fragments:
            # Check if this fragment is common
            is_common = False
            for common_frag in common:
                if abs(frag - common_frag) <= tolerance:
                    is_common = True
                    break
            if not is_common:
                unique.append(frag)
        unique_fragments[enzyme_name][seq_name] = unique
    
    print(f"  Common fragments (~{tolerance}bp tolerance): {common_fragments[enzyme_name]}")
    print(f"  Number of common fragments: {len(common)}")
    
    for seq_name in sequences.keys():
        num_unique = len(unique_fragments[enzyme_name][seq_name])
        if num_unique > 0:
            print(f"  {seq_name}: {num_unique} unique - {unique_fragments[enzyme_name][seq_name]}")

# 3) Merged gel showing only differences
print("\n\n" + "="*70)
print("TASK C: MERGED ELECTROPHORESIS GEL (DIFFERENCES ONLY)")
print("="*70)

for enzyme_name in enzymes.keys():
    print(f"\n\n{enzyme_name} - Showing only unique fragments")
    print("="*70)
    
    has_differences = False
    
    for seq_name in sequences.keys():
        unique_frags = unique_fragments[enzyme_name][seq_name]
        
        if unique_frags:
            has_differences = True
            print(f"\n{seq_name}:")
            print("-" * 30)
            
            for frag_length in sorted(unique_frags, reverse=True):
                migration_distance = int((1 - frag_length / max_length) * gel_height)
                spaces = " " * migration_distance
                band = "█" * 10
                print(f"{spaces}{band}  {frag_length} bp")
    
    if not has_differences:
        print("\nNo differences - all genomes produce identical fragments")

# Summary statistics
print("\n\n" + "="*70)
print("SUMMARY STATISTICS")
print("="*70)

for enzyme_name in enzymes.keys():
    print(f"\n{enzyme_name}:")
    total_unique = sum(len(unique_fragments[enzyme_name][seq]) for seq in sequences.keys())
    print(f"  Total unique fragments across all genomes: {total_unique}")
    print(f"  Common fragments: {len(common_fragments[enzyme_name])}")
    
    genomes_with_unique = sum(1 for seq in sequences.keys() if len(unique_fragments[enzyme_name][seq]) > 0)
    print(f"  Genomes with unique fragments: {genomes_with_unique}/10")